### PR TITLE
Skip image copy if outside of OADP/CAM

### LINKED ISSUE #59: Backups fail when using plugin outside of OADP/CAM context
Information to reproduce (from user):
1. We added the plugin openshift-velero-plugin and tried a Velero backup on a namespace with a pod, pvc and a service.
2. The backup seems to fail with the following message:
```
time="2020-10-06T19:33:45Z" level=info msg="[is-backup] Error in getting route: resource name may not be empty" backup=velero-ppdm/dk-k8s-12-2020-10-06-12-33-31-dk-k8s-12 cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/backup.go:48" pluginName=velero-plugins
time="2020-10-06T19:33:45Z" level=info msg="1 errors encountered backup up item" backup=velero-ppdm/dk-k8s-12-2020-10-06-12-33-31-dk-k8s-12 logSource="pkg/backup/backup.go:451" name=dk-k8s-12-service
```
3. Prior to this we were getting an error as shown below. We temporarily created an empty configMap “oadp-registry-config” In Velero namespace and landed with the above error in point 2. Do we mandatorily need to create a configMap in velero namespace.
```
time="2020-10-06T07:02:00Z" level=info msg="[is-backup] Error in getting route: configmaps \"oadp-registry-config\" not found" backup=velero-ppdm/test-os-2020-10-06-00-01-39-test-os cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/backup.go:48" pluginName=velero-plugins
time="2020-10-06T07:02:00Z" level=info msg="1 errors encountered backup up item" backup=velero-ppdm/test-os-2020-10-06-00-01-39-test-os
```

My thoughts:

I believe we introduced a regression when we merged the OADP work here. The intention was that if we didn't find the registry annotations we would simply assume we cannot backup the images in the cluster and we should just skip the IS plugins. We should also be documenting how a user can supply the needed information manually if they wish to include the image backups without using OADP/CAM.

### PR DESCRIPTION
**Pull request by dymurray**

### CODE REVIEW

File: velero-plugins/common/types.go [hunk 1]
```diff
@@ -19,6 +19,8 @@ const RestoreServerVersion string = "openshift.io/restore-server-version"
 const BackupRegistryHostname string = "openshift.io/backup-registry-hostname"
 const RestoreRegistryHostname string = "openshift.io/restore-registry-hostname"
 
+const SkipImages string = "openshift.io/skip-images"
```
Comment (sseago) [inline velero-plugins/common/types.go:22]: Our newer annotations tend to use "migration.openshift.io" -- should we move to that here as well?

**Review by sseago — COMMENTED** [review]
Looks good overall, although we need to figure out how to handle istags as well -- might as well include that in this PR since it's related.

**Review by JaydipGabani — APPROVED** [review]
Looks good! 
Just a thought, we can implement the same without adding a new annotation, just don't set `MigrationRegistry` if we don't find the registry route and assume that it's running outside of OADP and CAM

File: velero-plugins/common/types.go (hunk 1 above)
Comment (shubham-pampattiwar) [reply velero-plugins/common/types.go:22]: +1

Comment (dymurray) [reply velero-plugins/common/types.go:22]: My thought process was to not use migration since this would be set outside of CAM/OADP context. But fine to do that if you think it's better

**Comment by dymurray** [comment]
@JaydipGabani I considered that as well. Definitely not a bad idea. My thought was perhaps we want to evaluate some backups/restores and determine which context they were run in so we'd want an annotation to track.

**Review by JaydipGabani — APPROVED** [review]

**Review by sseago — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]
ACK
